config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only:%i[create]

  resources :gyms, only: %i[show index] do
    resources :comments, only: %i[create edit update destroy], module: :gyms
  end

  resources :trainers, only: %i[index show] do
    resources :comments, only: %i[create edit update destroy], module: :trainers
    resources :likes, only: %i[create destroy]
  end

  devise_for :users
  resources :users, only: [:show]
  # resources :users, only: [:show] do
  #   resources :comments, only: %i[create edit update destroy], module: :users
  # end

    resources :comments, only: %i[create edit update destroy]
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  mount_uploader :image_name, ImageUploader

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_trainers, through: :likes, source: :trainer
  
  enum sex: { man: 0, woman: 1}

  def already_liked?(trainer)
    self.likes.exists?(trainer_id: trainer.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :image_name, :sex])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :image_name, :sex])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.preload(:trainer).all.page(params[:page]).per(4).order('updated_at DESC')
    @trainers = @user.liked_trainers.preload(trainer_categories: :category, comments: :user).all.page(params[:page]).per(6)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comments.html.erb
<% @comments.each do |comment| %>

    <div class="row comment-">

        <div class="col-md-2 comment-icon">
            <%= image_tag(comment.user.image_name.url) unless comment.user.blank?%>
            <h6><%= comment.user.name unless comment.user.blank? %></h6>
        </div>

        <div class="col-md-6 comment-content">
            <div id="star-rate-<%= comment.id %>">評価　</div>
            <h5><%= comment.title %></h5>
            <p><%= comment.content %></p>
            <% if user_signed_in? && comment.user == current_user %>
            <div class="comment-li">
                <p><%= link_to '削除', comment_path(comment), method: :delete %></p>
                <p>/</p>
                <p><%= link_to '編集', edit_comment_path(comment) %></p>
            </div>
            <% end %>
        </div>

            <script>
                $('#star-rate-<%= comment.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= comment.rate %>,
                });
            </script>

        <div class="col-md-4 comment-info text-center">
            <% if comment.gym_id.nil? %>
                <%= link_to trainer_path(comment.trainer) do%>
                    <%= image_tag(comment.trainer.image.url, {class: "trainer-img"})%>
                    <p><%= comment.trainer.name %></p>
                <%end%>
            <%else%>
                <%= link_to gym_path(comment.gym) do %>
                    <%= image_tag(comment.gym.image.url, {class: "gym-img"}) %>
                    <p><%= comment.gym.name %></p>
                <%end%>
            <%end%>
            <div class="new-gyms-time">
            <p><%= comment.created_at.strftime("%Y-%m-%d") %></p>
            </div>
        </div>
    </div>
<% end %>

<p><%= @user.comments.count %>件の口コミが表示されています。</p>

app/views/users/show.html.erb
<div class="container">

    <div class="user-profile">
        <div class="user-img">
            <%= image_tag(@user.image_name.url) %>
        </div>
        <div class="user-profile">
            <h4><%= @user.name %></h4>
            <p><%= @user.email %></p>
            <div class="home-profile">
                <p class="inline-block"><%= sex(@user.sex) %>：</p>
                <p class="inline-block"><%= age(@user.age) %></p>
            </div>
            <% if @user == current_user %>
                <%= link_to "プロフィールを編集する", edit_user_registration_url(@user), class: 'btn btn-primary'%>
            <% end %>
        </div>
    </div>

    <div class='tabs'>
        <div class='user-tab-buttons'>
            <span class='content1'>口コミ</span>
            <span class='content2'>お気に入り</span>
            <div id='user-lamp' class='content1'></div>
        </div>

        <div class='tab-content'>
            
            <div class='content1'>
                <%= render 'comments' %>
                <%= paginate @comments %>
            </div><!--content1-->
            
            <div class='content2'>
                <div class="row justify-content-center">
                    <%= render 'trainers/trainers-index' %>
                </div>
                <%= paginate @trainers %>
            </div><!--content2-->

        </div><!--tab-content-->

    </div><!--tabs-->

    <div class='credit'>
    </div>
    
</div><!--container-->

<script>
$('.tab-content>div').hide();
$('.tab-content>div').first().slideDown();
  $('.user-tab-buttons span').click(function(){
    var thisclass=$(this).attr('class');
    $('#user-lamp').removeClass().addClass('#user-lamp').addClass(thisclass);
    $('.tab-content>div').each(function(){
      if($(this).hasClass(thisclass)){
        $(this).fadeIn(800);
      }
      else{
        $(this).hide();
      }
    });
  });
</script>