config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only:%i[create]

  resources :gyms, only: %i[show index] do
    resources :comments, only: %i[create edit update destroy], module: :gyms
  end

  resources :trainers, only: %i[index show] do
    resources :comments, only: %i[create edit update destroy], module: :trainers
    resources :likes, only: %i[create destroy]
  end

  devise_for :users
  resources :users, only: [:show]
  # resources :users, only: [:show] do
  #   resources :comments, only: %i[create edit update destroy], module: :users
  # end

    resources :comments, only: %i[create edit update destroy]
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :gym_categories
    has_many :gyms, through: :gym_categories
    has_many :trainer_categories
    has_many :trainers, through: :trainer_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, presence: true
  belongs_to :user, optional: true
  belongs_to :gym, optional: true
  belongs_to :trainer, optional: true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true, length: {maximum:255},
                        format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    validates :message, presence: true
end

app/models/district.rb
class District < ApplicationRecord
    
    has_many :gyms
    accepts_nested_attributes_for :gyms, allow_destroy: true

    has_many :trainer_districts
    has_many :trainers, through: :trainer_districts
    accepts_nested_attributes_for :trainer_districts, allow_destroy: true

end

app/models/gym.rb
class Gym < ApplicationRecord
    validates :district_id, presence: true
    validates :title, length: { maximum: 180 }
    
    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    has_many :item_images, dependent: :destroy
    mount_uploader :image, ImageUploader
    
    has_many :gym_categories
    has_many :categories, through: :gym_categories, source: :category, dependent: :destroy
    accepts_nested_attributes_for :gym_categories, allow_destroy: true

    has_many :gym_trainers
    has_many :trainers, through: :gym_trainers, dependent: :destroy
    accepts_nested_attributes_for :gym_trainers, allow_destroy: true

    belongs_to :district, optional: true

    has_many :comments, dependent: :destroy

    ransacker :comments_count do
        query = '(SELECT COUNT(comments.gym_id) FROM comments where comments.gym_id = gyms.id GROUP BY comments.gym_id)'
        Arel.sql(query)
    end
    
end

app/models/gym_category.rb
class GymCategory < ApplicationRecord
    belongs_to :gym, optional: true
    belongs_to :category, optional: true
end

app/models/gym_trainer.rb
class GymTrainer < ApplicationRecord
  belongs_to :gym, optional: true
  belongs_to :trainer, optional: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
    belongs_to :gym, optional: true
    mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :trainer, optional: true
  validates_uniqueness_of :trainer_id, scope: :user_id
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :title, length: { maximum: 180 }
  mount_uploader :image, ImageUploader

  has_many :trainer_categories
  has_many :categories, through: :trainer_categories, dependent: :destroy
  accepts_nested_attributes_for :trainer_categories, allow_destroy: true

  has_many :gym_trainers
  has_many :gyms, through: :gym_trainers, dependent: :destroy
  accepts_nested_attributes_for :gym_trainers, allow_destroy: true

  has_many :trainer_districts
  has_many :districts, through: :trainer_districts, dependent: :destroy
  accepts_nested_attributes_for :trainer_districts, allow_destroy: true

  has_many :comments, dependent: :destroy

  has_many :likes
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  enum sex: { 男性: 0, 女性: 1}
  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    end
  end

  ransacker :comment_count do
    query = '(SELECT COUNT(comments.trainer_id) FROM comments where comments.trainer_id = trainers.id GROUP BY comments.trainer_id)'
    Arel.sql(query)
  end

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.trainer_id) FROM likes where likes.trainer_id = trainers.id GROUP BY likes.trainer_id)'
    Arel.sql(query)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  mount_uploader :image_name, ImageUploader

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_trainers, through: :likes, source: :trainer
  
  enum sex: { man: 0, woman: 1}

  def already_liked?(trainer)
    self.likes.exists?(trainer_id: trainer.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/district_helper.rb
module DistrictHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="main-content">
        <div class="left box">
            <h2>About us</h2>
            <div class="content">
                <p>こちらのサービスはポートフォリオです。</p>
                <div class="social">
                    <a href="https://github.com/Takayaus/toretomo"><span class="fab fa-github"></span></a>
                </div>
            </div>
        </div>
        <div class="center box">
            <h2>Address</h2>
            <div class="content">
                <div class="place">
                    <span class="fas fa-map-marker-alt"></span>
                    <span class="text">Osaka,</span>
                </div>
                <div class="phone">
                    <span class="fas fa-phone-alt"></span>
                    <span class="text">000-0000-0000</span>
                </div>
                <div class="email">
                    <span class="fas fa-envelope"></span>
                    <span class="text">morit617@gmail.com</span>
                </div>
            </div>
        </div>
        <div class="right box">
            <h2>Contact us</h2>
            <div class="content">
                <% @contact = Contact.new %>
                <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :email, '返信先メールアドレス' %>
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :message, 'お問い合わせ内容' %>
                    <%= f.text_area :message, class: 'form-control' %>
                </div>
                <%= f.submit '送信', class: 'btnn'%>
                <% end %>
            </div>
        </div>
    </div>
    <div class="bottom">
        <center>
            <span class="far fa-copyright"></span><span>2020 All right reserved.</span>
        </center>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="back"></div>
<header>
  <label><a class="log" href="/">ToreTomo</a></label>
  <ul>
    <li><a class="list" href="/">home</a></li>
    <li><a class="list" href="/gyms">ジム一覧</a></li>
    <li><a class="list" href="/trainers">トレーナー一覧</a></li>
    <li><a class="list" href="/admin/login">管理者</a></li>
    <% if user_signed_in? %>
      <li><a class="list" href="/users/sign_out">ログアウト</a></li>
      <li><a class="active list" href="/users/<%= current_user.id %>">アカウント</a></li>
    <% else %>
      <li><a class="list" href="/users/sign_in">ログイン</a></li>
      <li><a class="active list" href="/users/sign_up">新規登録</a></li>
    <% end %>
  </ul>
  <label id ="ico">
    <i class="fas fa-bars"></i>
  </label>
</header>

<script>
  $(document).ready(function(){
    $('#ico').click(function(){
      $('ul').toggleClass('show');
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToreTomo</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/css/swiper.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/183144ea57.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <div id="wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_comment-form.html.erb
<% if @comments.present? %>
  <% @comments.each do |comment| %>
    <div class="row comment-">

      <div class="col-md-2 comment-icon">
        <%= image_tag(comment.user.image_name.url) unless comment.user.blank?%>
        <h6><%= comment.user.name unless comment.user.blank? %></h6>
      </div>

      <div class="col-md-10 comment-content">
        <div id="star-rate-<%= comment.id %>">評価　</div>
        <h5><%= comment.title %></h5>
        <p><%= comment.content %></p>
      </div>

      <% if user_signed_in? && comment.user == current_user %>
        <div class="comment-li">
          <p><%= link_to '削除', gym_comment_path(gt, comment), method: :delete %></p>
          <p>/</p>
          <p><%= link_to '編集', edit_gym_comment_path(gt, comment) %></p>
        </div>
      <% end %>
      
      <div class="new-gyms-time">
        <p><%= comment.created_at.strftime("%Y-%m-%d") %></p>
      </div>
        <script>
          $('#star-rate-<%= comment.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= comment.rate %>,
          });
        </script>
    
    </div><!--row-comment---->
  <% end %>
<% end %>

app/views/shared/_trainers-swiper.html.erb
  <div class="swiper-">
    <div class="swiper-container">
      <h2 class="heading">評価の高いトレーナー</h2>
      <div class="swiper-wrapper">
        <% @trainers.each do |trainer| %>
          <div class="swiper-slide">
            <div class="slide-item">
            <a class="link" href="/trainers/<%= trainer.id %>"></a>
              <div class="slide-top">
                <div class="slide-left">
                  <a href="/trainers/<%= trainer.id %>"><%= image_tag (trainer.image.url) %></a>
                </div>
                <div class="slide-right">
                  <h6><%= trainer.name %></h6>
                    <p id="star-ave<%= trainer.id %>"></p>
                        <script>
                        $('#star-ave<%= trainer.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= trainer.comments.average(:rate).to_f.round(1) %>,
                          });
                        </script>
                    <p>(<%= trainer.comments.count %>)</p></br>
                    <% trainer.trainer_categories.each do |tra| %>
                      <li class="tras-cate"><%= link_to tra.category.name, trainers_path(q: {categories_id_in: tra.category_id }) unless tra.category.nil? %></li>
                    <% end %>
                </div>
              </div><!--slide-top-->
              <div class="slide-middle">
                <% if trainer.title.length > 40 %>
                  <p class="read"><%= trainer.title %></p>
                <% else %>
                  <p><%= trainer.title %></p>
                <% end %>
                <script>
                  $(function () {
                    $('.read').readmore({
                    speed: 100,
                    collapsedHeight: 45,
                    moreLink: '<a href="#">続きを読む</a>',
                    lessLink: '<a href="#">閉じる</a>'
                    });
                  });
                </script>
              </div>
              <div class="slide-bottom">
                <% trainer.comments.reverse.first(1).each do |comment| %>
                  <div id="star-rate-<%= comment.id %>"></div>
                    <% if comment.content.length > 40 %>
                      <p class="read"><%= comment.content %></p>
                    <% else %>
                      <p><%= comment.content %></p>
                    <% end %>
                    <script>
                      $('#star-rate-<%= comment.id %>').raty({
                      size: 30,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= comment.rate %>,
                      });
                    </script>
                  <div class="profile">
                    <p> (<%= sex(comment.user.sex) %></p>
                    <p><%= age(comment.user.age) %>)</p>
                    <p><%= comment.created_at.strftime("%Y-%m-%d") %></p>
                  </div>
                <% end %>
                <div class="tras-like">
                  <% if user_signed_in? %>
                    <% if current_user.already_liked?(trainer) %>
                      <%= link_to trainer_like_path(trainer, trainer), method: :delete, remote: :true do %>
                        <i class="fa fa-heart" aria-hidden="true" style="color: red;">
                          <%= trainer.likes.count %> 
                        </i>
                      <% end %>
                    <% else %>
                      <%= link_to trainer_likes_path(trainer, trainer), method: :post, remote: :true do %>
                        <i class="fa fa-heart" aria-hidden="true" style="color: #C0C0C0;">
                          <%= trainer.likes.count %> 
                        </i>
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;">
                      <%= trainer.likes.count %>
                    </i>
                  <% end %>
                </div>
              </div><!--slide-bottom-->
            </div><!--slide-item-->
          </div><!--swiper-slide-->
        <% end %>
      </div><!--swiper-wrapper-->
	  </div><!--swiper-container-->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  </div><!--swiper-->