config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only:%i[create]

  resources :gyms, only: %i[show index] do
    resources :comments, only: %i[create edit update destroy], module: :gyms
  end

  resources :trainers, only: %i[index show] do
    resources :comments, only: %i[create edit update destroy], module: :trainers
    resources :likes, only: %i[create destroy]
  end

  devise_for :users
  resources :users, only: [:show]
  # resources :users, only: [:show] do
  #   resources :comments, only: %i[create edit update destroy], module: :users
  # end

    resources :comments, only: %i[create edit update destroy]
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :gym_categories
    has_many :gyms, through: :gym_categories
    has_many :trainer_categories
    has_many :trainers, through: :trainer_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, presence: true
  belongs_to :user, optional: true
  belongs_to :gym, optional: true
  belongs_to :trainer, optional: true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true, length: {maximum:255},
                        format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    validates :message, presence: true
end

app/models/district.rb
class District < ApplicationRecord
    
    has_many :gyms
    accepts_nested_attributes_for :gyms, allow_destroy: true

    has_many :trainer_districts
    has_many :trainers, through: :trainer_districts
    accepts_nested_attributes_for :trainer_districts, allow_destroy: true

end

app/models/gym.rb
class Gym < ApplicationRecord
    validates :district_id, presence: true
    validates :title, length: { maximum: 180 }
    
    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    has_many :item_images, dependent: :destroy
    mount_uploader :image, ImageUploader
    
    has_many :gym_categories
    has_many :categories, through: :gym_categories, source: :category, dependent: :destroy
    accepts_nested_attributes_for :gym_categories, allow_destroy: true

    has_many :gym_trainers
    has_many :trainers, through: :gym_trainers, dependent: :destroy
    accepts_nested_attributes_for :gym_trainers, allow_destroy: true

    belongs_to :district, optional: true

    has_many :comments, dependent: :destroy

    ransacker :comments_count do
        query = '(SELECT COUNT(comments.gym_id) FROM comments where comments.gym_id = gyms.id GROUP BY comments.gym_id)'
        Arel.sql(query)
    end
    
end

app/models/gym_category.rb
class GymCategory < ApplicationRecord
    belongs_to :gym, optional: true
    belongs_to :category, optional: true
end

app/models/gym_trainer.rb
class GymTrainer < ApplicationRecord
  belongs_to :gym, optional: true
  belongs_to :trainer, optional: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
    belongs_to :gym, optional: true
    mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :trainer, optional: true
  validates_uniqueness_of :trainer_id, scope: :user_id
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :title, length: { maximum: 180 }
  mount_uploader :image, ImageUploader

  has_many :trainer_categories
  has_many :categories, through: :trainer_categories, dependent: :destroy
  accepts_nested_attributes_for :trainer_categories, allow_destroy: true

  has_many :gym_trainers
  has_many :gyms, through: :gym_trainers, dependent: :destroy
  accepts_nested_attributes_for :gym_trainers, allow_destroy: true

  has_many :trainer_districts
  has_many :districts, through: :trainer_districts, dependent: :destroy
  accepts_nested_attributes_for :trainer_districts, allow_destroy: true

  has_many :comments, dependent: :destroy

  has_many :likes
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  enum sex: { 男性: 0, 女性: 1}
  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    end
  end

  ransacker :comment_count do
    query = '(SELECT COUNT(comments.trainer_id) FROM comments where comments.trainer_id = trainers.id GROUP BY comments.trainer_id)'
    Arel.sql(query)
  end

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.trainer_id) FROM likes where likes.trainer_id = trainers.id GROUP BY likes.trainer_id)'
    Arel.sql(query)
  end

end

app/models/trainer_category.rb
class TrainerCategory < ApplicationRecord
  belongs_to :trainer, optional: true
  belongs_to :category, optional: true
end

app/models/trainer_district.rb
class TrainerDistrict < ApplicationRecord
  belongs_to :trainer, optional: true
  belongs_to :district, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  mount_uploader :image_name, ImageUploader

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_trainers, through: :likes, source: :trainer
  
  enum sex: { man: 0, woman: 1}

  def already_liked?(trainer)
    self.likes.exists?(trainer_id: trainer.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/gyms/comments_controller.rb
class Gyms::CommentsController < CommentsController

  private

    def set_commentable  
      @commentable = Gym.find(params[:gym_id])  
    end  

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController

  def index
    @q = Gym.ransack(params[:q])
    @gyms = @q.result(distinct: true).includes(:district, :categories).page(params[:page]).per(GYM_PAGE)
    @districts = District.all
    @categories = Category.all
    end


  def show
    @gym = Gym.preload(:item_images, trainers: {trainer_categories: :category, comments: :user}, gym_categories: :category).find(params[:id])
    @comments = @gym.comments.preload(:user).all.page(params[:page]).per(4).order('updated_at DESC')
    @comment = @gym.comments.build
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/district_helper.rb
module DistrictHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gyms/_gyms-index.html.erb
<% @gyms.each do |gym|%>

    <div class="gyms-item"> 
    <a class="link" href="/gyms/<%= gym.id %>"></a>
        <div class="gyms-title">
            <h5><%= truncate(gym.name, omission: '..', length: 40) %> </h5>
        </div>
        <div class="gyms-box">
            <div class="gyms-left">
                <a href="/gyms/<%= gym.id %>"><%= image_tag (gym.image.url) %></a>
            </div>
            <div class="gyms-right">
                <div class="gyms-star">
                    <p id="star-ave<%= gym.id %>">評価</p>
                    <p>(口コミ数<%= gym.comments.count %>)</p>
                </div>
                    <script>
                        $('#star-ave<%= gym.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= gym.comments.average(:rate).to_f.round(1) %>,
                        });
                    </script>
                <% gym.gym_categories.each do |g| %>
                    <%= link_to g.category.name, gyms_path(q: {categories_id_in: g.category_id }), {class: "gyms-content"} %>
                <% end %>
                </br><p class="gyms-content"><%= gym.address %></p></br>
                <p class="gyms-content">月会費：<%= gym.price %></p>
                    <% if gym.title.length > 40 %>
                        <p class="read"><%= gym.title %></p>
                    <% else %>
                        <p><%= gym.title %></p>
                    <% end %>
                    <script>
                        $(function () {
                            $('.read').readmore({
                            speed: 100,
                            collapsedHeight: 45,
                            moreLink: '<a href="#">続きを読む</a>',
                            lessLink: '<a href="#">閉じる</a>'
                            });
                        });
                    </script>                            
            </div><!--gyms-right-->
        </div><!--gyms-box-->
        <div class="gyms-button">
            <i class="fa fa-phone" aria-hidden="true" style="color: #0080ff;" ></i> <%=gym.number%>
            <a href="#" class="btn-flat-simple">
                <i class="fa fa-caret-right"></i> HPで詳しく見る
            </a>
        </div>
    </div><!--gyms-item-->

    <!--スマホ用-->
        <div class="gyms-card" style="width: 18rem;">
            <a class="link" href="/gyms/<%= gym.id %>"></a>
            <%= image_tag(gym.image.url, size: '286x180') %>
            <p class="district-name"><%= gym.district.name unless gym.district.nil?%></p>
            <div class="gyms-card-body">
                <div class="gyms-star">
                    <p id="star_ave<%= gym.id %>">評価 </p>
                    <p>(口コミ数<%= gym.comments.count %>)</p>
                </div>
                    <script>
                        $('#star_ave<%= gym.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= gym.comments.average(:rate).to_f.round(1) %>,
                        });
                    </script>
                <h5 class="gyms-card-title"><%= truncate(gym.name, omission: '..', length: 20) %></h5>
                <p class="gyms-card-text"><%= truncate(gym.title, omission: '..', length: 70) %></p>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <% gym.gym_categories.each do |g| %>
                            <%= link_to g.category.name, gyms_path(q: {categories_id_in: g.category_id }), {class: "gyms-content"} %>
                        <% end %>
                    </li>
                    <li class="list-group-item"><p class="gyms-content">月会費：<%= gym.price %></p></li>
                    <li class="list-group-item"><i class="fa fa-phone" aria-hidden="true" style="color: #0080ff;" ></i> <%=gym.number%></li>
                </ul>
            </div>
        </div>
                        <script>
                        $('#star_ave<%= gym.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= gym.comments.average(:rate).to_f.round(1) %>,
                        });
                    </script>
<% end %>

app/views/gyms/_gyms-nav.html.erb
    <nav class="gyms-nav">
        <ul>
            <li class=”current”><%= link_to 'トップ', gym_path(@gym) %></li>
            <li><%= link_to '写真', gym_item_images_path(@gym) %></li>
            <li><%= link_to '口コミ', gym_path(@gym) %></li>
            <li><%= link_to 'アクセス', gym_path(@gym) %></li>
        </ul>
    </nav>

app/views/gyms/index.html.erb
<div class="container">
    <button type="button" class="btn btn-primary gyms-ran" style="text-align:center; ">詳細検索</button>
    <div class="gyms-contents">
        <aside class="gyms-side">
            <div class="gyms-ransack">
                <%= search_form_for @q do |f| %>
                    <div class="form-group">
                        <i class="fas fa-sort"></i>
                        <%= f.label "並び替え" %></br>
                        <%= f.select( :sorts, { '': 'id desc', '料金の安い順': 'price asc', '料金の高い順': 'price desc', '古い順': 'updated_at asc', '新しい順': 'updated_at desc', '口コミの多い順': 'comments_count desc'}) %>
                    </div>
                    <div class="form-group">
                        <i class="fas fa-search-minus"></i>
                        <%= f.label :name, "キーワード" %>
                        <%= f.search_field :name_or_title_or_content_or_address_or_categories_name_cont %>
                    </div>
                    <div class="form-group">
                        <i class="fas fa-map-marker-alt"></i>
                        <%= f.label :district_id_eq, "エリア" %></br>
                        <%= f.collection_select :district_id_eq, @districts, :id, :name, include_blank: true %>
                    </div>
                    <div class="form-group">
                        <i class="fas fa-align-left"></i>
                        <%= f.label :categories_id_in, "カテゴリー" %></br>
                        <%= f.collection_check_boxes :categories_id_in, @categories, :id, :name do |b|%>
                            <%= b.label {b.check_box + b.text} %>
                        <% end %>
                    </div>
                    <div class="form-group">
                        <i class="fas fa-yen-sign"></i>
                        <%= f.label :price, '月会費' %></br>
                        <%= f.number_field :price_gteq %>〜
                        <%= f.number_field :price_lt %>未満
                    </div>
                        <%= f.submit "検索", class: 'btn btn-success btn-sub'%>
                <% end %>
            </div>
        </aside>

        <div class="gyms-items">
            <% if @gyms.empty? %>
                <p>検索結果 0件： 他のキーワードで検索してみよう！</p>
            <% elsif params[:q] %>
                <div style="text-align:center; width:650px;"><p>検索結果 <%= @gyms.total_count %>件</p></div>
                <%= render 'gyms/gyms-index' %>
            <%else%>
                <%= render 'gyms/gyms-index' %>
            <% end %>
            <%= paginate @gyms %>
        </div>
    </div>
</div>

<script>
$(function(){
$(".gyms-ran").on("click", function() {
$('.gyms-side').slideToggle();
});
});
</script>

app/views/gyms/show.html.erb
<div class="container">

  <div class="gym-wrapper">
    <div class="row">
      <div class="col-md-6 col-xs-12 gym-right">
        <h3><%= @gym.name %></h3>
        <div class="gym-rate">
          <p id="star-ave">評価　</p>
          <p>(口コミ数<%= @gym.comments.count %>)</p>
        </div>
        <script>
        $('#star-ave').raty({
        size: 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        half: true,
        readOnly: true,
        score: <%= @gym.comments.average(:rate).to_f.round(1) %>,
          });
        </script>
        <p><%= @gym.title %></p>
        <p class="district-name"><%= @gym.district.name unless @gym.district.nil?%></p>
        <p><%= @gym.address %></p>
        <% if @gym.number? %>
          <i class="fa fa-phone" aria-hidden="true" style="color: #0080ff;" ></i>
          <%= @gym.number %></br>
        <%end%>
        <% @gym.gym_categories.each do |g|%>
          <%= link_to g.category.name, gyms_path(q: {categories_id_in: g.category_id }), {class: "gyms-content"} %>
        <% end %>
      </div>
      <div class="col-md-6 col-xs-12 gym-left">
        <%= image_tag(@gym.image.url, class: "img-fluid img-thumbnail") %>
      </div>
    </div>
  </div>


  <div class='tabs'>
    <div class='tab-buttons'>
      <span class='content1'>ホーム</span>
      <span class='content2'>写真</span>
      <span class='content3'>口コミ</span>
      <span class='content4'>地図</span>
      <div id='lamp' class='content1'></div>
    </div>
    <div class='tab-content'>
      
      <div class='content1'>
        <div class="gym-content">
          <% text = @gym.content %>
          <%= markdown(text).html_safe %>
        </div>
      </div>
      
      <div class='content2'>
        <div class="contain">
          <% @gym.item_images.each do |item_image| %>
              <div class="items-item">
                <div class="real">
                  <%= link_to item_image.image.url, 'data-lightbox': item_image.image do %>
                    <%= image_tag item_image.image.url  if item_image.image? %>
                  <%end%>
                </div>
              </div>
          <%end%>
        </div>
      </div>
      
      <div class='content3'>
        <%= render 'shared/comment-form', gt: @gym %>
        <%= paginate @comments %>
                <%= form_with(model: [@gym, @comment], local: true, remote: true) do |f| %>
                <div class="form-group">
                  <%= f.label :title, "タイトル" %>
                  <%= f.text_area :title, class: "form-control", rows: 1 %>
                </div>

                <div class="form-group">
                  <%= f.label :content, "内容" %>
                  <%= f.text_area :content, class: "form-control", rows: 5 %>
                </div>

                <div class="form-group" id="star">
                  <%= f.label :rate,'評価' %>
                  <%= f.hidden_field :rate, id: :comment_star %>
                </div>

                <script>
                  $('#star').raty({
                    size     : 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    scoreName: 'comment[rate]',
                    half: true,
                    });
                </script>

                <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
                  <i class="far fa-comments"></i> コメントする
                <% end %>
              <% end %>
      </div><!--content3-->

      <div class='content4'>
        <% if @gym.address.empty? %>
          <h4>位置情報はまだ登録されていません。</h4>
        <% else %>
          <h4>位置情報</h4>
          <div id='map'></div>
        <% end %>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api %>&callback=initMap" async defer></script>
        <script>
        function initMap(){
          let m = {lat: <%= @gym.latitude %>, lng: <%= @gym.longitude %>};
          let map = new google.maps.Map(document.getElementById('map'), {
            center: m,
          zoom: 16
          });
              var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            var contentString = '住所：<%= @gym.address %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });

            var marker = new google.maps.Marker({
              position: m,
              map: map,
              title: contentString
            });
        }
        window.onload = function () {
    initMap();
}
        </script>
      </div>
        
    </div><!--tab-content-->
  </div><!--tabs-->
  <% if @gym.gym_trainers.empty? %>
    <h5>トレーナーの登録がありません</h5>
  <% else %>
    <div class="swiper-">
      <div class="swiper-container">
        <h2 class="heading">施設利用可能なトレーナー</h2>
        <div class="swiper-wrapper">
          <% @gym.gym_trainers.each do |gym| %>
            <div class="swiper-slide">
              <div class="slide-item">
              <a class="link" href="/trainers/<%= gym.trainer.id %>"></a>
                <div class="slide-top">
                  <div class="slide-left">
                    <a href="/trainers/<%= gym.trainer.id %>"><%= image_tag (gym.trainer.image.url) %></a>
                  </div>
                  <div class="slide-right">
                    <h6><%= gym.trainer.name %></h6>
                      <p id="star-ave<%= gym.trainer.id %>"></p>
                          <script>
                          $('#star-ave<%= gym.trainer.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn : '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          half: true,
                          readOnly: true,
                          score: <%= gym.trainer.comments.average(:rate).to_f.round(1) %>,
                            });
                          </script>
                      <p>(<%= gym.trainer.comments.count %>)</p></br>
                      <% gym.trainer.trainer_categories.each do |tra| %>
                        <li class="tras-cate"><%= link_to tra.category.name, trainers_path(q: {categories_id_in: tra.category_id }) unless tra.category.nil? %></li>
                      <% end %>
                  </div>
                </div><!--slide-top-->
                <div class="slide-middle">
                  <% if gym.trainer.title.length > 40 %>
                    <p class="read"><%= gym.trainer.title %></p>
                  <% else %>
                    <p><%= gym.trainer.title %></p>
                  <% end %>
                  <script>
                    $(function () {
                      $('.read').readmore({
                      speed: 100,
                      collapsedHeight: 45,
                      moreLink: '<a href="#">続きを読む</a>',
                      lessLink: '<a href="#">閉じる</a>'
                      });
                    });
                  </script>
                </div>
                <div class="slide-bottom">
                  <% gym.trainer.comments.reverse.first(1).each do |comment| %>
                    <div id="star-rate-<%= comment.id %>"></div>
                      <% if comment.content.length > 40 %>
                        <p class="read"><%= comment.content %></p>
                      <% else %>
                        <p><%= comment.content %></p>
                      <% end %>
                      <script>
                        $('#star-rate-<%= comment.id %>').raty({
                        size: 30,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= comment.rate %>,
                        });
                      </script>
                    <div class="profile">
                      <p> (<%= sex(comment.user.sex) %></p>
                      <p><%= age(comment.user.age) %>)</p>
                      <p><%= comment.created_at.strftime("%Y-%m-%d") %></p>
                    </div>
                  <% end %>
                  <div class="tras-like">
                    <% if user_signed_in? %>
                      <% if current_user.already_liked?(gym.trainer) %>
                        <%= link_to trainer_like_path(gym.trainer, gym.trainer), method: :delete, remote: :true do %>
                          <i class="fa fa-heart" aria-hidden="true" style="color: red;">
                            <%= gym.trainer.likes.count %> 
                          </i>
                        <% end %>
                      <% else %>
                        <%= link_to trainer_likes_path(gym.trainer, gym.trainer), method: :post, remote: :true do %>
                          <i class="fa fa-heart" aria-hidden="true" style="color: #C0C0C0;">
                            <%= gym.trainer.likes.count %> 
                          </i>
                        <% end %>
                      <% end %>
                    <% else %>
                      <i class="fa fa-heart" aria-hidden="true" style="color: red;">
                        <%= gym.trainer.likes.count %>
                      </i>
                    <% end %>
                  </div>
                </div><!--slide-bottom-->
              </div><!--slide-item-->
            </div><!--swiper-slide-->
          <% end %>
        </div><!--swiper-wrapper-->
        <div class="swiper-pagination"></div>
      </div><!--swiper-container-->
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    </div><!--swiper-->
  <% end %>
</div><!--container-->


<script>
$('.tab-content>div').hide();
$('.tab-content>div').first().slideDown();
  $('.tab-buttons span').click(function(){
    var thisclass=$(this).attr('class');
    $('#lamp').removeClass().addClass('#lamp').addClass(thisclass);
    $('.tab-content>div').each(function(){
      if($(this).hasClass(thisclass)){
        $(this).fadeIn(800);
      }
      else{
        $(this).hide();
      }
    });
  });
</script>
<script>
var mySwiper = new Swiper('.swiper-container', {
  slidesPerView: 1,
    breakpoints: {
    375: {
      slidesPerView: 1.1,
    },
    405: {
      slidesPerView: 1.2,
    },
    433: {
      slidesPerView: 1.3,
    },
    495: {
      slidesPerView: 1.5,
    },
    530: {
      slidesPerView: 1.6,
    },
    768: {
      slidesPerView: 2.2,
    },
    992: {
      slidesPerView: 3,
    },
    1200: {
      slidesPerView: 3.1,
    }
  },
    navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
	autoplay: {
		delay: 10000,
		stopOnLastSlide: false,
		disableOnInteraction: false,
    reverseDirection: false,
    centeredSlides : true
  },	
  pagination: {
		el: '.swiper-pagination',
		type: 'fraction',
	}
  
});
</script>